#!/usr/bin/env python3
"""Give every archival mirror a provenance header, so none of them looks like a re-upload.

WHY. A peer review generated by our own served model (Qwen3.8-27B at 1M, 30 subagents) flagged
that `Qwen3.8-27B-exl3-archival-d32ba0bb` carried the upstream README verbatim with no mirror or
provenance note. Auditing all seven mirrors showed the problem was wider than reported: FOUR of
seven had no note, and revealingly they are exactly the four that no card cites. An archival
mirror without a provenance header is indistinguishable from an unattributed re-upload of someone
else's work, which is the opposite of why we mirror.

The upstream README is preserved verbatim BELOW the banner - it is their card and their words. We
only prepend attribution, and add the `archival-mirror` tag that the three correctly-documented
mirrors already carry.

Provenance comes from `receipts/shortlist-shard0.json` -> `artifacts.<key>.{upstream_repo,
upstream_revision,mirror}`, which records per-file re-verification (LFS oid sha256 for LFS files,
git blob sha1 for small files, both computed from local bytes).

Usage:
    fix_mirror_provenance.py            # audit only, exit 1 if any mirror lacks a note
    fix_mirror_provenance.py --apply    # prepend the banner and upload
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HF_HOME = "/var/tmp/hf-home-3"

# artifact key in shortlist-shard0.json -> a one-line description of what the upstream is
DESCRIPTIONS = {
    "awq": "an AWQ INT4 quantisation",
    "saka": "an NVFP4 quantisation carrying MTP weights",
    "turbo5": "an EXL3 quantisation",
    "turbo6": "an EXL3 quantisation",
}


def hf(*argv: str) -> str:
    env = {"HF_HOME": HF_HOME, "PATH": "/home/mbelleau/.local/bin:/usr/bin:/bin",
           "HOME": "/home/mbelleau"}
    p = subprocess.run(["hf", *argv], capture_output=True, text=True, env=env)
    if p.returncode != 0:
        raise SystemExit(f"hf {' '.join(argv)} failed rc={p.returncode}\n{p.stdout[-1500:]}\n{p.stderr[-1500:]}")
    return p.stdout.strip()


def banner(mirror_repo: str, upstream_repo: str, upstream_rev: str, desc: str,
           verification: str) -> str:
    short = upstream_rev[:8]
    return f"""# Archival mirror of [`{upstream_repo}`](https://huggingface.co/{upstream_repo}) at revision `{short}`

> [!IMPORTANT]
> **This is not our work and it is not a new quantisation.** It is a byte-identical archival mirror
> of [`{upstream_repo}`](https://huggingface.co/{upstream_repo}) — {desc} — pinned at revision
> [`{upstream_rev}`](https://huggingface.co/{upstream_repo}/tree/{upstream_rev}).
> Nothing was requantised, re-exported, converted or edited. **Use the upstream repository for
> anything current**; this exists only so that a published measurement of ours stays checkable.
>
> **Why it exists.** We compared this artifact against our own builds and published the numbers.
> A Hub revision can stop resolving — history gets squashed, repositories get renamed or removed —
> and when that happens a published comparison becomes unverifiable. Pinning the exact bytes we
> measured keeps the claim falsifiable by anyone, including against us.
>
> **Verification.** {verification}
>
> **Credit for the artifact below belongs to its original author.** The README that follows is
> theirs, reproduced verbatim; only this banner was added.

---

"""


def load_provenance() -> dict:
    d = json.loads((REPO_ROOT / "receipts" / "shortlist-shard0.json").read_text())
    out = {}
    for key, art in (d.get("artifacts") or {}).items():
        m = art.get("mirror") or {}
        if not m.get("repo"):
            continue
        out[m["repo"]] = {
            "key": key,
            "upstream_repo": art.get("upstream_repo"),
            "upstream_revision": art.get("upstream_revision"),
            "verification": m.get("verification", ""),
        }
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="prepend banners and upload (default: audit)")
    a = ap.parse_args()

    import os
    os.environ["HF_HOME"] = HF_HOME
    from huggingface_hub import HfApi, hf_hub_download

    api = HfApi()
    prov = load_provenance()
    mirrors = sorted(m.id for m in api.list_models(author="malaiwah") if "archival" in m.id)

    missing = []
    for repo in mirrors:
        try:
            p = hf_hub_download(repo, "README.md", repo_type="model")
            text = Path(p).read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            print(f"{repo:52} NO README ({type(e).__name__})")
            continue
        has_note = "archival mirror" in text.lower() or "archival-mirror" in text.lower()
        print(f"{repo:52} provenance_note={'yes' if has_note else 'NO'}")
        if not has_note:
            missing.append((repo, text))

    if not missing:
        print("\nall mirrors carry a provenance note")
        return 0
    print(f"\n{len(missing)} mirror(s) lack a provenance note")
    if not a.apply:
        print("re-run with --apply to fix")
        return 1

    for repo, text in missing:
        pr = prov.get(repo)
        if not pr or not pr.get("upstream_repo"):
            print(f"  SKIP {repo}: no provenance record in receipts/shortlist-shard0.json - refusing to invent one")
            continue
        head = banner(repo, pr["upstream_repo"], pr["upstream_revision"],
                      DESCRIPTIONS.get(pr["key"], "a third-party quantisation"),
                      pr["verification"])
        # Insert after YAML front matter so Hub metadata keeps working; add the tag the
        # correctly-documented mirrors already carry.
        m = re.match(r"^(---\n.*?\n---\n)(.*)$", text, re.DOTALL)
        if m:
            fm, body = m.group(1), m.group(2)
            if "archival-mirror" not in fm:
                fm = re.sub(r"\ntags:\n", "\ntags:\n- archival-mirror\n", fm, count=1)
                if "archival-mirror" not in fm:  # no tags block at all
                    fm = fm[:-4] + "tags:\n- archival-mirror\n---\n"
            new = fm + "\n" + head + body.lstrip("\n")
        else:
            new = head + text

        scratch = Path("/var/tmp") / f"mirror-readme-{repo.split('/')[-1]}"
        scratch.mkdir(parents=True, exist_ok=True)
        (scratch / "README.md").write_text(new, encoding="utf-8")
        hf("upload", repo, str(scratch / "README.md"), "README.md", "--repo-type", "model",
           "--commit-message", "Add an archival-mirror provenance banner; upstream README preserved verbatim below")
        print(f"  banner added to {repo}")

    # verify
    print("\nverifying:")
    still = 0
    for repo, _ in missing:
        p = hf_hub_download(repo, "README.md", repo_type="model", force_download=True)
        ok = "archival mirror" in Path(p).read_text(encoding="utf-8", errors="replace").lower()
        print(f"  {repo:52} {'OK' if ok else 'STILL MISSING'}")
        still += 0 if ok else 1
    return 0 if still == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
